version: 2.1

orbs:
  node: circleci/node@4.1.0
  gcp-gcr: circleci/gcp-gcr@0.11.0
  cloud-run: circleci/gcp-cloud-run@1.0.2

jobs:
  test-node-with-docker:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - node/install:
          install-yarn: true
          node-version: 8.17.0 
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: 
          name: Run tests
          command: yarn test
  deploy-to-cloud-run:
    executor: cloud-run/default
    steps:
      - cloud-run/init:
          gcloud-service-key: gcp_service_account_key
          google-project-id: gcp_project_id
      - cloud-run/deploy:
          image: "gcr.io/${gcp_project_id}/frontendapi:<< pipeline.git.tag >>"
          region: ${gcp_region}
          service-name: api-service
          unauthenticated: true

workflows:
  version: 2
  run-unit-tests:
    jobs:
      - test-node-with-docker:
          filters:
            tags:
              ignore: /.*/
  deploy-on-tag:
    jobs:
      - gcp-gcr/build-and-push-image:
          context: "Quest Tracker Data"
          filters: &deploy-filters
            branches:
              ignore: /.*/
            tags:
              only: /^\d\.\d\.\d$/
          gcloud-service-key: gcp_service_account_key
          google-project-id: gcp_project_id
          image: frontendapi
          tag: << pipeline.git.tag >>
      - deploy-to-cloud-run:
          context: "Quest Tracker Data"
          filters:
            <<: *deploy-filters
          requires:
            - gcp-gcr/build-and-push-image

